const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..');

function read(relativePath) {
  return fs.readFileSync(path.join(root, relativePath), 'utf8');
}

function browserModule(source, exportName, exportExpression) {
  return source.replace(/module\.exports\s*=\s*\{[\s\S]*?\};\s*$/, `globalThis.${exportName} = ${exportExpression};`);
}

const lunar = read('node_modules/lunar-javascript/lunar.js')
  .replace('})(this,function(){', '})(globalThis,function(){');

const profile = browserModule(
  read('lib/profile.js'),
  'WendaoProfile',
  '{ FOCUS_OPTIONS, LOCATION_KEYS, birthplaceLabel, inferLegacyBirthplace, normalizeBirthplaceDetail, sanitizeFocus }'
);

const fortune = browserModule(
  read('lib/fortune.js').replace("const { Solar } = require('lunar-javascript');", 'const { Solar } = globalThis;'),
  'WendaoFortune',
  '{ AGENTS, calculateProfile, buildLocalReading, buildOverviewReadings, buildDailyReading }'
);

const localApi = `
;(function () {
  const { AGENTS, calculateProfile, buildLocalReading, buildOverviewReadings, buildDailyReading } = globalThis.WendaoFortune;
  const { FOCUS_OPTIONS, birthplaceLabel, normalizeBirthplaceDetail, sanitizeFocus } = globalThis.WendaoProfile;

  function parseRequestBody(options) {
    if (!options || !options.body) return {};
    if (typeof options.body === 'string') return JSON.parse(options.body);
    return options.body;
  }

  function normalizeUser(body = {}) {
    if (!body.name || !body.birthDate || !body.birthTime) throw new Error('请完整填写姓名、出生日期和时间');
    const birthplaceDetail = normalizeBirthplaceDetail(body.birthplaceDetail, body.birthplace);
    if (!birthplaceDetail.country || !birthplaceDetail.province || !birthplaceDetail.city) {
      throw new Error('请至少填写出生国家、省份和城市');
    }
    const user = {
      id: String(body.id || ('profile-' + Date.now().toString(36))).slice(0, 80),
      name: String(body.name).trim().slice(0, 20),
      gender: String(body.gender || '未填写').slice(0, 10),
      birthDate: String(body.birthDate).slice(0, 10),
      birthTime: String(body.birthTime).slice(0, 5),
      birthplace: birthplaceLabel(birthplaceDetail),
      birthplaceDetail,
      focus: sanitizeFocus(body.focus),
      member: Boolean(body.member),
      createdAt: body.createdAt || new Date().toISOString()
    };
    user.profile = calculateProfile(user);
    return user;
  }

  function routePath(pathname) {
    return String(pathname || '').split('?')[0];
  }

  async function request(pathname, options = {}) {
    const path = routePath(pathname);
    const body = parseRequestBody(options);

    if (path === '/api/health') return { ok: true, service: 'wendao-static', storageMode: 'device' };
    if (path === '/api/bootstrap') {
      return { agents: Object.values(AGENTS), focusOptions: FOCUS_OPTIONS, aiConnected: false, storageMode: 'device' };
    }
    if (path === '/api/profile') return { user: normalizeUser(body.user || body) };
    if (path === '/api/overview') {
      const user = normalizeUser(body.user);
      return { summaries: buildOverviewReadings(user, body.historyByAgent || {}) };
    }
    if (path === '/api/reading') {
      const user = normalizeUser(body.user);
      const agent = AGENTS[body.agentId];
      if (!agent || body.agentId === 'daily') throw new Error('Agent 类型无效');
      const question = String(body.question || '').trim().slice(0, 500);
      if (!question) throw new Error('请输入想测算的问题');
      const history = Array.isArray(body.history) ? body.history.slice(-40) : [];
      const reading = buildLocalReading(user, body.agentId, question, history);
      return { reading: { ...reading, detailsLocked: !user.member } };
    }
    if (path === '/api/daily') {
      const user = normalizeUser(body.user);
      const history = Array.isArray(body.history) ? body.history.slice(-30) : [];
      return { reading: buildDailyReading(user, history) };
    }
    if (path === '/api/unlock') return { user: normalizeUser({ ...body.user, member: true }) };
    throw new Error('接口不存在');
  }

  globalThis.WendaoLocalApi = { request };
})();
`;

const output = [
  '/* Generated by npm run build:static. Do not edit directly. */',
  lunar,
  `;(function () {\n${profile}\n})();`,
  `;(function () {\n${fortune}\n})();`,
  localApi
].join('\n\n');

fs.writeFileSync(path.join(root, 'public/local-engine.js'), output);
console.log(`Built public/local-engine.js (${Buffer.byteLength(output)} bytes)`);
